FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY apps/api/package*.json ./apps/api/
COPY packages/ ./packages/
RUN npm install
COPY apps/api/ ./apps/api/
RUN npm run build --workspace=apps/api
EXPOSE 4000
CMD ["npm", "start", "--workspace=apps/api"]
